### ISSUE TITLE
bootstrap4

### ISSUE THREAD

**Issue by nguyenduylinhqbu** [CodingMantras/django-object-detection#7]
Dear sir,
Where is the bootstrap4 folder inside the template?
Error: "/django-object-detection/templates/bootstrap4/uni_form.html (Source does not exist)"
Thanks.

**Comment by rampal-punia** [comment]
Hi, The error was due to an update in Django-crispy-forms. The repo is updated now accordingly. Clone the newer version of this repo and install `crispy-bootstrap4` along with other packages. A description of the same can be found in the `readme` file also.

Thanks for reporting the issue.

**Comment by nguyenduylinhqbu** [comment]
Dear sir @CodingMantras,
I got it.
Thank you very much.
Best regards
